# generated by wxGlade 0.6.8 on Wed Dec 23 14:57:56 2015
#
# To get wxPerl visit http://wxPerl.sourceforge.net/
#

use Wx 0.15 qw[:allclasses];
use strict;
# begin wxGlade: dependencies
use Wx::Locale gettext => '_T';
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package AMGui::Base::MainFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;


sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: AMGui::Base::MainFrame::new
    $style = wxDEFAULT_FRAME_STYLE 
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    

    # Menu Bar

    $self->{mainFrame_menubar} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $wxglade_tmp_menu = Wx::Menu->new();
    $wxglade_tmp_menu->Append(wxID_NEW, _T("&New\tCtrl+N"), "");
    $wxglade_tmp_menu->Append(wxID_OPEN, _T("&Open\tCtrl+O"), "");
    $wxglade_tmp_menu->AppendSeparator();
    $wxglade_tmp_menu->Append(wxID_EXIT, _T("&Quit\tCtrl+Q"), "");
    $self->{_T("mainFrame_menubar")}->Append($wxglade_tmp_menu, _T("&File"));
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{_T("mainFrame_menubar")}->Append($wxglade_tmp_menu, _T("&Edit"));
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{_T("mainFrame_menubar")}->Append($wxglade_tmp_menu, _T("&Run\tCtrl+R"));
    $wxglade_tmp_menu = Wx::Menu->new();
    $wxglade_tmp_menu->Append(wxID_HELP_CONTENTS, _T("Help\tCtrl+H"), "");
    $wxglade_tmp_menu->AppendSeparator();
    $wxglade_tmp_menu->Append(wxID_ABOUT, _T("About"), "");
    $self->{_T("mainFrame_menubar")}->Append($wxglade_tmp_menu, _T("&Help"));
    $self->SetMenuBar($self->{mainFrame_menubar});
    
# Menu Bar end

    $self->{mainFrame_statusbar} = $self->CreateStatusBar(1, 0);
    $self->{window_1} = Wx::SplitterWindow->new($self, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_BORDER);
    $self->{leftWindow} = Wx::Panel->new($self->{window_1}, wxID_ANY, wxDefaultPosition, wxDefaultSize, );
    $self->{rightWindow} = Wx::Panel->new($self->{window_1}, wxID_ANY, wxDefaultPosition, wxDefaultSize, );
    $self->{notebook_2} = Wx::Notebook->new($self->{rightWindow}, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0);
    $self->{notebook_2_pane_1} = Wx::Panel->new($self->{notebook_2}, wxID_ANY, wxDefaultPosition, wxDefaultSize, );

    $self->__set_properties();
    $self->__do_layout();

    # end wxGlade
    return $self;

}


sub __set_properties {
    my $self = shift;
    # begin wxGlade: AMGui::Base::MainFrame::__set_properties
    $self->SetTitle(_T("Main Frame"));
    $self->SetSize(Wx::Size->new(690, 511));
    $self->{mainFrame_statusbar}->SetStatusWidths(-1);

	my( @mainFrame_statusbar_fields ) = (
		_T("Status Bar")
	);

    if( @mainFrame_statusbar_fields ) {
    	$self->{mainFrame_statusbar}->SetStatusText($mainFrame_statusbar_fields[$_], $_)
		for 0 .. $#mainFrame_statusbar_fields ;
	}
    # end wxGlade
}

sub __do_layout {
    my $self = shift;
    # begin wxGlade: AMGui::Base::MainFrame::__do_layout
    $self->{sizer_1} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{notebook_2}->AddPage($self->{notebook_2_pane_1}, _T("tab1"));
    $self->{sizer_2}->Add($self->{notebook_2}, 1, wxEXPAND, 0);
    $self->{rightWindow}->SetSizer($self->{sizer_2});
    $self->{window_1}->SplitVertically($self->{leftWindow}, $self->{rightWindow}, );
    $self->{sizer_1}->Add($self->{window_1}, 1, 0, 0);
    $self->SetSizer($self->{sizer_1});
    $self->Layout();
    # end wxGlade
}

# end of class AMGui::Base::MainFrame

1;

