# generated by wxGlade 0.7.1 on Sat Jan 16 19:19:05 2016
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx 0.15 qw[:allclasses];
use strict;
# begin wxGlade: dependencies
use Wx::Locale gettext => '_T';
# end wxGlade

# begin wxGlade: extracode
use AMGui::Constants;
# end wxGlade

package AMGui::Base::MainFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

# begin wxGlade: dependencies
use Wx::Locale gettext => '_T';
# end wxGlade

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: AMGui::Base::MainFrame::new
    $style = wxDEFAULT_FRAME_STYLE 
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    

    # Menu Bar

    $self->{mainFrame_menubar} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $wxglade_tmp_menu = Wx::Menu->new();
    $wxglade_tmp_menu->Append(wxID_NEW, _T("&New\tCtrl+N"), "");
    $wxglade_tmp_menu->Append(wxID_OPEN, _T("&Open\tCtrl+O"), "");
    $wxglade_tmp_menu->AppendSeparator();
    $wxglade_tmp_menu->Append(wxID_EXIT, _T("&Quit\tCtrl+Q"), "");
    $self->{mainFrame_menubar}->Append($wxglade_tmp_menu, _T("&File"));
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{mainFrame_menubar}->Append($wxglade_tmp_menu, _T("&Edit"));
    $wxglade_tmp_menu = Wx::Menu->new();
    $wxglade_tmp_menu->Append(1000, _T("&Run AM\tCtrl+R"), "");
    $self->{mainFrame_menubar}->Append($wxglade_tmp_menu, _T("&Run"));
    $wxglade_tmp_menu = Wx::Menu->new();
    $wxglade_tmp_menu->Append(wxID_HELP_CONTENTS, _T("Help\tCtrl+H"), "");
    $wxglade_tmp_menu->AppendSeparator();
    $wxglade_tmp_menu->Append(wxID_ABOUT, _T("About"), "");
    $self->{mainFrame_menubar}->Append($wxglade_tmp_menu, _T("&Help"));
    $self->SetMenuBar($self->{mainFrame_menubar});
    
    # Menu Bar end

    $self->{mainFrame_statusbar} = $self->CreateStatusBar(1);
    $self->{window_1} = Wx::SplitterWindow->new($self, wxID_ANY);
    $self->{leftWindow} = Wx::Panel->new($self->{window_1}, wxID_ANY);
    $self->{rightWindow} = Wx::Notebook->new($self->{window_1}, wxID_ANY);
    $self->{lbFileData} = Wx::ListBox->new($self->{rightWindow}, wxID_ANY, wxDefaultPosition, wxDefaultSize, [_T("Load data from a file")], wxLB_SINGLE);

    $self->__set_properties();
    $self->__do_layout();

    # end wxGlade
    return $self;

}


sub __set_properties {
    my $self = shift;
    # begin wxGlade: AMGui::Base::MainFrame::__set_properties
    $self->SetTitle(_T("Main Frame"));
    $self->SetSize(Wx::Size->new(690, 511));
    $self->{mainFrame_statusbar}->SetStatusWidths(-1);

    # statusbar fields
    my( @mainFrame_statusbar_fields ) = (
        _T("Status Bar"),
    );

    if( @mainFrame_statusbar_fields ) {
        $self->{mainFrame_statusbar}->SetStatusText($mainFrame_statusbar_fields[$_], $_)
        for 0 .. $#mainFrame_statusbar_fields ;
    }
    $self->{lbFileData}->SetSelection(0);
    # end wxGlade
}

sub __do_layout {
    my $self = shift;
    # begin wxGlade: AMGui::Base::MainFrame::__do_layout
    $self->{sizer_1} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{rightWindow}->AddPage($self->{lbFileData}, _T("NoFile"));
    $self->{window_1}->SplitVertically($self->{leftWindow}, $self->{rightWindow}, );
    $self->{sizer_1}->Add($self->{window_1}, 1, wxEXPAND, 0);
    $self->SetSizer($self->{sizer_1});
    $self->Layout();
    # end wxGlade
}

# end of class AMGui::Base::MainFrame

1;

