# generated by wxGlade 0.7.0 on Mon Dec 14 20:46:56 2015
#
# To get wxPerl visit http://www.wxperl.it
#

package AMGui::Base::MainFrame;

use Wx 0.15 qw[:allclasses];
use strict;
# begin wxGlade: dependencies
use Wx::Locale gettext => '_T';
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: AMGui::Base::MainFrame::new
    $style = wxDEFAULT_FRAME_STYLE 
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->{combo_box_1} = Wx::ComboBox->new($self, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, [_T("apples"), _T("potatoes"), _T("gurken")], wxCB_DROPDOWN|wxCB_READONLY|wxCB_SORT);
    $self->{calendar_ctrl_1} = Wx::CalendarCtrl->new($self, wxID_ANY, Wx::DateTime->new);
    

    # Menu Bar

    $self->{mainFrame_menubar} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $wxglade_tmp_menu = Wx::Menu->new();
    $wxglade_tmp_menu->Append(wxID_NEW, _T("&New\tCtrl+N"), "");
    $wxglade_tmp_menu->Append(wxID_OPEN, _T("&Open\tCtrl+O"), "");
    $wxglade_tmp_menu->AppendSeparator();
    $wxglade_tmp_menu->Append(wxID_EXIT, _T("&Quit\tCtrl+Q"), "");
    $self->{_T("mainFrame_menubar")}->Append($wxglade_tmp_menu, _T("&File"));
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{_T("mainFrame_menubar")}->Append($wxglade_tmp_menu, _T("&Edit"));
    $wxglade_tmp_menu = Wx::Menu->new();
    $wxglade_tmp_menu->Append(wxID_HELP_CONTENTS, _T("Help\tCtrl+H"), "");
    $wxglade_tmp_menu->AppendSeparator();
    $wxglade_tmp_menu->Append(wxID_ABOUT, _T("About"), "");
    $self->{_T("mainFrame_menubar")}->Append($wxglade_tmp_menu, _T("&Help"));
    $self->SetMenuBar($self->{mainFrame_menubar});
    
    # Menu Bar end

    $self->{mainFrame_statusbar} = $self->CreateStatusBar(1);

    $self->__set_properties();
    $self->__do_layout();

    # end wxGlade
    return $self;

}


sub __set_properties {
    my $self = shift;
    # begin wxGlade: AMGui::Base::MainFrame::__set_properties
    $self->SetTitle(_T("Main Frame"));
    $self->SetSize(Wx::Size->new(400, 500));
    $self->{combo_box_1}->SetSelection(1);
    $self->{mainFrame_statusbar}->SetStatusWidths(-1);

    # statusbar fields
    my( @mainFrame_statusbar_fields ) = (
        _T("Status Bar"),
    );

    if( @mainFrame_statusbar_fields ) {
        $self->{mainFrame_statusbar}->SetStatusText($mainFrame_statusbar_fields[$_], $_)
        for 0 .. $#mainFrame_statusbar_fields ;
    }
    # end wxGlade
}

sub __do_layout {
    my $self = shift;
    # begin wxGlade: AMGui::Base::MainFrame::__do_layout
    $self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sizer_1}->Add($self->{combo_box_1}, 0, wxALL, 0);
    $self->{sizer_1}->Add($self->{calendar_ctrl_1}, 0, 0, 0);
    $self->SetSizer($self->{sizer_1});
    $self->Layout();
    # end wxGlade
}

# end of class AMGui::Base::MainFrame

1;

